version: '3.0'

services:
  mongors1n1:
    container_name: mongors1n1
    image: mongo
    command: mongod --shardsvr --replSet mongors1 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - ./scripts:/scripts
      - /etc/localtime:/etc/localtime:ro
      - ugc_mongo_cluster_data1:/data/db

  mongors2n1:
    container_name: mongors2n1
    image: mongo
    command: mongod --shardsvr --replSet mongors2 --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - ./scripts:/scripts
      - /etc/localtime:/etc/localtime:ro
      - ugc_mongo_cluster_data4:/data/db

  mongocfg1:
    container_name: mongocfg1
    image: mongo
    command: mongod --configsvr --replSet mongors1conf --dbpath /data/db --port 27017
    expose:
      - "27017"
    volumes:
      - ./scripts:/scripts
      - /etc/localtime:/etc/localtime:ro
      - ugc_mongo_cluster_config1:/data/db

  mongos1:
    container_name: mongos1
    image: mongo
    depends_on:
      - mongocfg1
    command: mongos --configdb mongors1conf/mongocfg1:27017 --port 27017 --bind_ip_all
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - ./scripts:/scripts
      - /etc/localtime:/etc/localtime:ro

  db:
    container_name: postgres_db
    image: postgres:14.1-alpine3.15
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      POSTGRES_DB: "ugc_postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./sql_scripts/:/docker-entrypoint-initdb.d/

volumes:
  ugc_mongo_cluster_data1:
  ugc_mongo_cluster_data4:
  ugc_mongo_cluster_config1:
  postgres_data: