# Generated by Django 3.2.9 on 2021-11-08 12:38

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='FilmWork',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created'),
                ),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                (
                    'description',
                    models.TextField(blank=True, null=True, verbose_name='Description'),
                ),
                (
                    'creation_date',
                    models.DateField(blank=True, null=True, verbose_name='Creation date'),
                ),
                (
                    'certificate',
                    models.TextField(blank=True, null=True, verbose_name='Certificate'),
                ),
                (
                    'file_path',
                    models.FileField(
                        blank=True, null=True, upload_to='film_works/', verbose_name='File'
                    ),
                ),
                (
                    'rating',
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name='Rating',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[('movie', 'Movie'), ('tv_show', 'TV Show')],
                        default='movie',
                        max_length=25,
                        verbose_name='Type',
                    ),
                ),
            ],
            options={
                'verbose_name': 'FilmWork',
                'verbose_name_plural': 'FilmWorks',
                'db_table': 'content"."film_work',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='FilmWorkGenre',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created'),
                ),
            ],
            options={
                'verbose_name': 'FilmWorkGenre',
                'verbose_name_plural': 'FilmWorksGenres',
                'db_table': 'content"."genre_film_work',
            },
        ),
        migrations.CreateModel(
            name='FilmWorkPerson',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('actor', 'Actor'),
                            ('director', 'Director'),
                            ('writer', 'Writer'),
                        ],
                        default='actor',
                        max_length=25,
                        verbose_name='Role',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created'),
                ),
            ],
            options={
                'verbose_name': 'FilmWorkPerson',
                'verbose_name_plural': 'FilmWorksPersons',
                'db_table': 'content"."person_film_work',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created'),
                ),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Title')),
                (
                    'description',
                    models.TextField(blank=True, null=True, verbose_name='Description'),
                ),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'db_table': 'content"."genre',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                (
                    'created_at',
                    models.DateTimeField(auto_now_add=True, verbose_name='Created'),
                ),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('full_name', models.CharField(max_length=255, verbose_name='Full name')),
                (
                    'birth_date',
                    models.DateField(blank=True, null=True, verbose_name='Birth date'),
                ),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'content"."person',
                'ordering': ('full_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(
                fields=('full_name', 'birth_date'), name='unique_person'
            ),
        ),
        migrations.AddField(
            model_name='filmworkperson',
            name='film_work',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork'
            ),
        ),
        migrations.AddField(
            model_name='filmworkperson',
            name='person',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='movies.person'
            ),
        ),
        migrations.AddField(
            model_name='filmworkgenre',
            name='film_work',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='movies.filmwork'
            ),
        ),
        migrations.AddField(
            model_name='filmworkgenre',
            name='genre',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='movies.genre'
            ),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='genres',
            field=models.ManyToManyField(
                blank=True,
                related_name='film_works',
                through='movies.FilmWorkGenre',
                to='movies.Genre',
            ),
        ),
        migrations.AddField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(
                blank=True,
                related_name='film_works',
                through='movies.FilmWorkPerson',
                to='movies.Person',
            ),
        ),
        migrations.AddConstraint(
            model_name='filmworkperson',
            constraint=models.UniqueConstraint(
                fields=('film_work', 'person', 'role'), name='unique_filmwork_person_role_link'
            ),
        ),
        migrations.AddConstraint(
            model_name='filmworkgenre',
            constraint=models.UniqueConstraint(
                fields=('film_work', 'genre'), name='unique_filmwork_genre_link'
            ),
        ),
    ]
